# Generated by Django 3.2.11 on 2022-01-31 18:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Use a clear and distinctive name for the route.', max_length=50, unique=True)),
                ('project', models.CharField(help_text='Use the Iv project code, for example INFR191089.', max_length=50)),
                ('routepoints', models.CharField(help_text='For now use Google Maps coordinates. "51.89236,4.55976:51.94200,4.48367".', max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('description', models.TextField(blank=True)),
                ('routeType', models.CharField(choices=[('fastest', 'fastest'), ('shortest', 'shortest'), ('eco', 'eco'), ('thrilling', 'thrilling')], default='fastest', help_text="Leave this at 'fastest' unless you know what you are doing.", max_length=10)),
                ('travelMode', models.CharField(choices=[('car', 'car'), ('truck', 'truck'), ('taxi', 'taxi'), ('bus', 'bus'), ('motorcycle', 'motorcycle'), ('bicycle', 'bicycle'), ('pedestrian', 'pedestrian')], default='car', help_text='The mode of travel for the requested route.', max_length=20)),
                ('traffic', models.BooleanField(default=True, help_text='Determines whether current traffic is used in route calculations.')),
                ('avoid', models.CharField(default='unpavedRoads', editable=False, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RouteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('travel_time', models.DecimalField(decimal_places=2, max_digits=9)),
                ('route_length', models.DecimalField(decimal_places=2, max_digits=9)),
                ('delay', models.DecimalField(decimal_places=2, max_digits=9)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='routemonitor.route')),
            ],
            options={
                'verbose_name': 'Route historical data',
                'verbose_name_plural': 'Route historical data',
                'get_latest_by': 'timestamp',
            },
        ),
    ]
