# Generated by Django 3.2.11 on 2022-01-31 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routemonitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Route',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='RouteHistory',
            new_name='RouteData',
        ),
        migrations.RenameField(
            model_name='routedata',
            old_name='route',
            new_name='project',
        ),
    ]
