# Generated by Django 3.2.11 on 2022-02-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routemonitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='avoid',
        ),
        migrations.RemoveField(
            model_name='project',
            name='routeType',
        ),
        migrations.RemoveField(
            model_name='project',
            name='traffic',
        ),
        migrations.RemoveField(
            model_name='project',
            name='travelMode',
        ),
        migrations.AddField(
            model_name='route',
            name='avoid',
            field=models.CharField(default='unpavedRoads', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='route',
            name='routeType',
            field=models.CharField(choices=[('fastest', 'fastest'), ('shortest', 'shortest'), ('eco', 'eco'), ('thrilling', 'thrilling')], default='fastest', help_text="Leave this at 'fastest' unless you know what you are doing.", max_length=10),
        ),
        migrations.AddField(
            model_name='route',
            name='traffic',
            field=models.BooleanField(default=True, help_text='Determines whether current traffic is used in route calculations'),
        ),
        migrations.AddField(
            model_name='route',
            name='travelMode',
            field=models.CharField(choices=[('car', 'car'), ('truck', 'truck'), ('taxi', 'taxi'), ('bus', 'bus'), ('motorcycle', 'motorcycle'), ('bicycle', 'bicycle'), ('pedestrian', 'pedestrian')], default='car', help_text='The mode of travel for the requested route.', max_length=20),
        ),
    ]
