# Generated by Django 3.2.11 on 2022-02-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routemonitor', '0003_auto_20220215_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(help_text='Gebruik een duidelijke naam. Bijvoorbeeld: Omleidingsroute via A58-A2 2022-W12', max_length=50, unique=True),
        ),
    ]
